# Market hours types:
MARKET_HOURS_DAY = "MARKET_HOURS_DAY"
MARKET_HOURS_PREMARKET = "MARKET_HOURS_PREMARKET"
MARKET_HOURS_AFTERMARKET = "MARKET_HOURS_AFTERMARKET"
MARKET_HOURS_CLOSED = "MARKET_HOURS_CLOSED"

# Message action types:
ACTION_STOCK_QUERY = "ACTION_STOCK_QUERY"
ACTION_STOCK_CHART = "ACTION_STOCK_CHART"
ACTION_STOCK_CHART_VOLUME = "ACTION_STOCK_CHART_VOLUME"
ACTION_STOCK_PT = "ACTION_STOCK_PT"
ACTION_STOCK_INFO = "ACTION_STOCK_INFO"
ACTION_STOCK_EARNINGS = "ACTION_STOCK_EARNINGS"
ACTION_STOCK_NEWS = "ACTION_STOCK_NEWS"




