# Market hours types:
MARKET_HOURS_DAY = "MARKET_HOURS_DAY"
MARKET_HOURS_PREMARKET = "MARKET_HOURS_PREMARKET"
MARKET_HOURS_AFTERMARKET = "MARKET_HOURS_AFTERMARKET"
MARKET_HOURS_CLOSED = "MARKET_HOURS_CLOSED"