# Market hours types:
MARKET_HOURS_DAY = "MARKET_HOURS_DAY"
MARKET_HOURS_PREMARKET = "MARKET_HOURS_PREMARKET"
MARKET_HOURS_AFTERMARKET = "MARKET_HOURS_AFTERMARKET"
MARKET_HOURS_CLOSED = "MARKET_HOURS_CLOSED"

# Message action types:
ACTION_TYPE_NONE = "ACTION_TYPE_NONE"
ACTION_TYPE_MSG = "ACTION_TYPE_MSG"
ACTION_STOCK_QUERY = "ACTION_STOCK_QUERY"
ACTION_CHART = "ACTION_CHART"
ACTION_CHART_VOLUME = "ACTION_CHART_VOLUME"
ACTION_PT = "ACTION_PT"
ACTION_INFO = "ACTION_INFO"
ACTION_EARNINGS = "ACTION_EARNINGS"
ACTION_NEWS = "ACTION_NEWS"
ACTION_OPTIONS = "ACTION_OPTIONS"

# Stock Charts Periods
STOCK_CHARTS_PERIODS = ["1d", "5d", "1mo", "3mo", "6mo", "1y", "2y", "5y", "10y", "ytd", "max"]
#Yfinance periods =  1d,5d,1mo,3mo,6mo,1y,2y,5y,10y,ytd,max

# Stock Green/Red Colors
COLOR_POSITIVE = 0x02d963
COLOR_NEGATIVE = 0xd90231
COLOR_NEUTRAL = 0X02a3d9
